# version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./backend:/app"
      - "/app/node_modules"
    networks:
      - app-network
    depends_on:
      - sphinx

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    stdin_open: true
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./frontend:/usr/src/app:delegated"
      - "/usr/src/app/node_modules/"
    networks:
      - app-network
    depends_on:
      - backend
  
  sphinx:
    build:
      context: ./sphinx
      dockerfile: Dockerfile
    container_name: sphinx
    environment:
      - SPHINX_CONFIG_FILE=/opt/sphinx/conf/sphinx_mushaf.conf
    ports:
      - 9306:9306
    volumes:
      - ./sphinx/data:/opt/sphinx/indexes
      - ./sphinx/sphinx_mushaf.conf:/opt/sphinx/conf/sphinx_mushaf.conf
      - ./sphinx/stopwords.txt:/opt/sphinx/conf/stopwords.txt
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge