# version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./backend:/app"
    networks:
      - app-network
    depends_on:
      - sphinx
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    stdin_open: true
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    depends_on:
      - backend

  sphinx:
    build:
      context: ./sphinx
      dockerfile: Dockerfile
    container_name: sphinx
    environment:
      - SPHINX_CONFIG_FILE=/opt/sphinx/conf/sphinx_mushaf.conf
    ports:
      - 9306:9306
    volumes:
      - ./sphinx/data:/opt/sphinx/indexes
      - ./sphinx/sphinx_mushaf.conf:/opt/sphinx/conf/sphinx_mushaf.conf
      - ./sphinx/stopwords.txt:/opt/sphinx/conf/stopwords.txt
    networks:
      - app-network

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qcms-password-k3y
      POSTGRES_DB: QCMS
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/backup/qcms_server_backup.sql:/backup/qcms_server_backup.sql
    networks:
      - app-network
    depends_on:
      - sphinx

networks:
  app-network:
    driver: bridge