# version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
    - sphinx

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - app-network
    depends_on:
      - backend
  
  sphinx:
    build:
      context: ./sphinx
      dockerfile: Dockerfile
    container_name: sphinx
    environment:
      - SPHINX_CONFIG_FILE=/opt/sphinx/conf/sphinx_mushaf.conf
    ports:
      - 9306:9306
    volumes:
      - ./sphinx/data:/opt/sphinx/indexes
      - ./sphinx/sphinx_mushaf.conf:/opt/sphinx/conf/sphinx_mushaf.conf
      - ./sphinx/stopwords.txt:/opt/sphinx/conf/stopwords.txt
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge